### ISSUE TITLE
[RFE] Support an update job type

### ISSUE THREAD

**Issue by smalleni** [cloud-bulldozer/kube-burner#121]
**Is your feature request related to a problem? Please describe.**
There are cases where we need to create a pod and subsequently update annotations on it for some of our scale testing. I'd like to see kube-burner support an `update` job type

**Describe the solution you'd like**
There should be an `update` job type that checks to see if the resource exists and if so updates it.

**Describe alternatives you've considered**
Currently we launch a side-car container in the pod that talks to kube-api and once the pod is up - annotates the pod.

**Additional context**

**Comment by smalleni** [comment]
@rsevilla87 thoughts on the feasibility here? If you'd consider this, we can request @jaredoconnell to help out with the implementation.

**Comment by smalleni** [comment]
@akrzos FYI

**Comment by rsevilla87** [comment]
Hey @smalleni , I wonder what is the use case of this feature request. In what situations you have to annotate a pod after creating it rather than creating it with the required annotations?

**Comment by smalleni** [comment]
@rsevilla87 These are ICNI2 specific operations where you need to annotate the gateway pods after they have been created for the ICNI2 magic to work.

**Comment by smalleni** [comment]
We are currently doing this by having a  side car container that updates annotations on the pod after the pod has been launched.

**Comment by rsevilla87** [comment]
Are those annotations something known upfront?

**Comment by smalleni** [comment]
> Are those annotations something known upfront?

Yes

**Comment by rsevilla87** [comment]
Ok, I think a better/easier solution would be to create a new `patch` job type to reproduce a behaviour similar to `kubectl patch`.
