### ISSUE TITLE
[RFE] Image preload

### ISSUE THREAD

**Issue by rsevilla87** [cloud-bulldozer/kube-burner#131]
**Is your feature request related to a problem? Please describe.**
It would be nice to provide kube-burner a image preload feature. This feature can be useful to ignore the noise caused by the container images pull process during the benchmark. This noise/delay is specially significant when measuring podLatency.

**Describe the solution you'd like**
A new option _imagePreload_ will be required. This new feature can work as described below:

- If preload is enabled, before starting the benchmark obtain the images from all containers the benchmark uses.
- Create a temporally namespace and temporally daemonset using those images to trigger image pulling from all nodes across the cluster.
- Wait for replicas to be ready (some of them can fail though)
- Delete all the temp stuff
- Continue with the regular behaviour

**Additional context**

Daemonsets will create a pod using th in all nodes matching the nodeSelector

**Comment by jaredoconnell** [comment]
@rsevilla87 Is there a specific way you had in mind to detect which images are being used? Or should they be listed separately?
