### ISSUE TITLE
[BUG] kube-burner crash with `fatal error: concurrent map writes`

### ISSUE THREAD

**Issue by gavin-stackrox** [cloud-bulldozer/kube-burner#144]
**Output of `kube-burner `version**
v0.14.1@3bda3fbde9a5a7b312ee4a474413e758358c362f

**Describe the bug**
Crash when indexing with `fatal error: concurrent map writes`. (full log attached).

**To Reproduce**
It is somewhat random.

**Expected behavior**
No crash.

[kb-pod-log.txt](https://github.com/cloud-bulldozer/kube-burner/files/7694932/kb-pod-log.txt)

**Comment by rsevilla87** [comment]
Hey @gavin-stackrox , I think this issue has been fixed by https://github.com/cloud-bulldozer/kube-burner/pull/142, which is included in the v0.14.3 version. Can you verify it?

**Comment by gavin-stackrox** [comment]
Hey @rsevilla87, there is an airflow run in [progress](http://airflow.apps.sailplane.perf.lab.eng.rdu2.redhat.com/graph?dag_id=4.10-aws-acs&run_id=scheduled__2022-01-10T12%3A00%3A00%2B00%3A00&execution_date=2022-01-10+12%3A00%3A00%2B00%3A00), I will keep an eye on it.

**Comment by gavin-stackrox** [comment]
Hi @rsevilla87, we are running into other issues in airflow (too many metrics) so I will assume that this is fixed. Thanks.
