### ISSUE TITLE
[RFE]   Add a new (example) workload to test end to end connectivity

### ISSUE THREAD

**Issue by numansiddique** [cloud-bulldozer/kube-burner#151]
The present example worklad - kubelet-density-heavy is really not helpful in testing the CNI plugin as postgre server pod can take a bit of time to come up as the number of iterations increase.

Just to test the CNI at the scale,  it would be great to add another workload very similar to kubelet-density-heavy,  but instead of the postgre app,  a simple nginx can can up and the app pod can curl to the service to report the pod readiness.

Perhaps even network policies can be added too.

**Comment by smalleni** [comment]
I'll try to take a first pass at it.
