### ISSUE TITLE
A lot of "completed" Pods when running Cluster Density

### ISSUE THREAD

**Issue by wolfganghuse** [cloud-bulldozer/kube-burner#168]
Hi, when running a Cluster Density Workload on Openshift 4.9 i see a lot of "completed" Pods from the Build-Tasks. These are filling up the Compute-Nodes. Is there any recommendation how to remove them asap to not interfere while running a Test ?

Regards,
Wolfgang

**Comment by rsevilla87** [comment]
Hey @wolfganghuse, this cluster creates a bunch of builds, if you're observing that you nodes are filling with those Completed pods, I suggest you to modify the workload to create other objects different from builds or maybe decreasing the number of these and increasing th number of deployments.
