### ISSUE TITLE
[BUG] podLatency Summary JSON not reflecting proper measurements

### ISSUE THREAD

**Issue by Noreen21** [cloud-bulldozer/kube-burner#181]
**Output of `kube-burner `version**
Version: 0.16
Git Commit: deaa2793742d9c89b8c277801a31912cddc2ab0d
Build Date: 2022-06-08T10:10:31Z
Go Version: go1.16.15
OS/Arch: linux amd64

**Describe the bug**
I have two jobs with job type "create" for pods in different namespaces. Both have the same kube-burner measurement configs, with pod latency measurements enabled. podLatency-summary.json is created for both namespaces, however, one of the namespace file only have "avg" of podLatencyQuantilesMeasurement and rest of the metrics (P99, P95, P50, and max) are not being populated and their value is 0. Similar file for the second job has data for both jobs (both namespaces) and all podLatency metrics are populated properly only for the second job/namespace.

**To Reproduce**

**Expected behavior**
Pod latency quantiles measurements are expected to be consistent for all jobs

**Screenshots or output**
If applicable, add screenshots or kube-burner output to help explain your problem.

**Additional context**
[kube-burner-measurements.zip](https://github.com/cloud-bulldozer/kube-burner/files/9395060/kube-burner-measurements.zip)

**Comment by Noreen21** [comment]
A couple more points to add:
1. The job that does not generate proper summary file only creates one pod which basically means podLatency metrics in the "job-name"-podLatency.json file and in the "jobname"-podLatency-summary.json file should technically be the same. Attaching an example "jobname"-podLatency.json for reference. 
2. Also found another issue with summary file of the second job which seemingly had all of P99, P95, P50 , max Pod latency Metrics. The calculated max values and P99 values are exactly the same in all files. Attaching an example scenario.
[boatload-bu-podLatency-files.zip](https://github.com/cloud-bulldozer/kube-burner/files/9466290/boatload-bu-podLatency-files.zip)
[boatload-podLatency-file.zip](https://github.com/cloud-bulldozer/kube-burner/files/9466291/boatload-podLatency-file.zip)

**Comment by rsevilla87** [comment]
Hey @Noreen21, as you can see I created a fix one of the issues you're reporting here. Now when executing benchmarks with multiple-jobs, the resulting metrics files will only have data from it's own job.

With respect the other issue you mentioned:

>  one of the namespace file only have "avg" of podLatencyQuantilesMeasurement and rest of the metrics (P99, P95, P50, and max) are not being populated and their value is 0.

I've realized that the job in question, "boatload", only deploys a pod. Hence kube-burner can't calculate these percentiles properly, resulting into 0. Can you verify that you don't see such behavior when deploying multiple pods?

**Comment by Noreen21** [comment]
Thanks for looking into this @rsevilla87 !  
1. So will be retaining the summary file with 0 values for the job with a single pod?
2. For job with multiple pods, I am noticing that the P99 and max values are exactly the same. If I screen the non-summary file for that job, I realize it is the max value that's been written for both (P99 and max). So, P99 value is not being calculated properly, from the looks of it.

**Comment by rsevilla87** [comment]
Can we close this one @Noreen21? Thanks!

**Comment by Noreen21** [comment]
Yes, we can. I couldn't test beyond a 100 workload pods though, but will open a new issue if I encounter it again in the future.
Thanks for all your help!
