### ISSUE TITLE
[RFE] Allow configurable namespace buckets

### ISSUE THREAD

**Issue by afcollins** [cloud-bulldozer/kube-burner#201]
**Is your feature request related to a problem? Please describe.**
kube-burner currently has a flag "namespacedIterations", which is a boolean that switches between only 1) all-in-one namespace for all workload iterations or 2) a distinct namespace for each iteration.
There is control plane overhead with creating a namespace, and this also means the creation rate of resources is rate-limited by the control plane, rather than the client QPS settings of kube-burner.

**Describe the solution you'd like**
I would like a knob that allows me to batch iterations into a fixed number of namespaces.
Could be implemented in many ways, but two ways to implement the knob might be: 1) Specifying a desired number of namespaces that the iterations are created in, or 2) Specifying the number of iterations per namespace to create.

This increased granularity added to namespacedIterations would also allow us to expand our understanding of cluster limits beyond the limits of a single namespace to the effects of multiple namespaces at the identified limits.

Extra credit:
Also, I may not always want to include the namespace creation in the workload measurement period.
There could be a separate flag to "prime" the namespaces, such that kube-burner creates all namespaces at once up front, then creates the workloads at the desired QPS rate.
This improvement allows us to have more desirable scale rate than what is currently limited by the instantiation time of a namespace.

**Comment by rsevilla87** [comment]
Revisiting this issue, I think this feature can be really interesting to define a number of namespaces in some of the well-known benchmarks (node-density-heavy?) and prevent creating all the pods in the same ns, which is not very representative as real case scenario.

**Comment by rsevilla87** [comment]
With respect to the create namespaces up front feature, it's not a breaking change in any manner, so 👍🏽

**Comment by afcollins** [comment]
Was a simpler change than I thought it would be. Opened a PR for it.
