### ISSUE TITLE
[Docs] Lack of documentation of OCP Wrapper

### ISSUE THREAD

**Issue by rsevilla87** [cloud-bulldozer/kube-burner#247]
**Is your feature request related to a problem? Please describe.**

Add documentation of workloads from the OCP wrapper

**Comment by paigerube14** [comment]
Can we update the ocp wrapper docs of what versions of kube-burner this option is available in

**Comment by paigerube14** [comment]
https://kube-burner.readthedocs.io/en/latest/ocp/
That version is not set up/available in the current e2e-benchmark version and that's what I had locally so couldn't find it

**Comment by rsevilla87** [comment]
right, e2e-benchmarking uses 0.17.2, there're some breaking changes in 1.0, for that reason I haven't bumped it
