### ISSUE TITLE
[RFE] Add more metadata to metric data

### ISSUE THREAD

**Issue by jtaleric** [cloud-bulldozer/kube-burner#250]
From : https://gist.github.com/jtaleric/e2d2b23fcd856d6dd5f5a88ff4b328bc#how-to-trend

```
We would want to capture some metadata, which would allow us to properly parse the result

platform (string)
version (string)
workload (string)
total node count (int)
encryption (bool)
ipsec (bool)
```
There are potentially more fields we would want to add.

**Comment by afcollins** [comment]
Agreed.
machine architecture is good to add also. Can be retrieved from the node label: `kubernetes.io/arch=arm64`

**Comment by jtaleric** [comment]
After more kicking of the tires, I noticed we also do not index the iterations as part of the metadata, we should add this too... it is however part of the `jobSummary`, but iterations should also be something we collect.

**Comment by jtaleric** [comment]
also, since some of our benchmarks implement the ability to churn we need to also collect the churn data as that can impact the results.

**Comment by jtaleric** [comment]
PR #253 is only a partial fix.. @rsevilla87 is working on another patch to add clusterMetadata.
