### ISSUE TITLE
[BUG] '--gc=false' works,  '--gc false' does not work

### ISSUE THREAD

**Issue by afcollins** [cloud-bulldozer/kube-burner#271]
**Output of `kube-burner `version**
Version: 1.4.3
Git Commit: a575df584a6b520a45e2fe7903e608a34e722e5f
Build Date: 2023-03-10T17:49:10Z
Go Version: go1.19.6
OS/Arch: linux amd64

**Describe the bug**
If I attempt to skip garbage collection, it only works if I assign with an equals: `--gc=false`

**To Reproduce**
1. kube-burner ocp node-density --gc false
2. kube-burner still garbage collects the namespace.

**Expected behavior**
kube-burner will not GC the namespace.

**Comment by rsevilla87** [comment]
This issue on spf13 seems related https://github.com/spf13/cobra/issues/1606

**Comment by afcollins** [comment]
Closing this issue as it is mostly a usability quirk.
