### ISSUE TITLE
[BUG] Authorization error creating Deployment ... is forbidden: failed to get namespace: namespace \"node-density-heavy-20621\" not found

### ISSUE THREAD

**Issue by afcollins** [cloud-bulldozer/kube-burner#277]
**Output of `kube-burner `version**
```
$ kube-burner version
Version: 1.4.3
Git Commit: a575df584a6b520a45e2fe7903e608a34e722e5f
Build Date: 2023-03-10T17:49:10Z
Go Version: go1.19.6
OS/Arch: linux amd64
```

**Describe the bug**
Kube-burner Fatal errors and quits if a namespace is not available when a deployment is created.

**To Reproduce**
1. kube-burner ocp node-density-heavy --extract
2. Set namespacedIterations: true
3. kube-burner ocp node-density-heavy --timeout 5h --metrics-endpoint metrics-endpoint.yml

**Expected behavior**
kube-burner does not exit if the namespace exists, but instead retries.

**Screenshots or output**
```
time="2023-03-22 18:12:05" level=info msg="Running job node-density-heavy"
time="2023-03-22 19:03:37" level=fatal msg="Authorization error creating Deployment/postgres-1-20621: deployments.apps \"postgres-1-20621\" is forbidden: failed to get namespace: namespace \"node-density-heavy-20621\" not found"
```

The creationTimestamp of the namespace is identical to the timestamp error message:
```
$ ogns node-density-heavy-20621 -o yaml
...
  creationTimestamp: "2023-03-22T19:03:37Z"
...
  name: node-density-heavy-20621
```

**Additional context**
Only just happened once out of 9 other runs on the same cluster, or 19 runs on this kube-burner version that have been 100% OK and never seen this problem.

**Comment by afcollins** [comment]
Just saw it again on the next execution.
```
time="2023-03-22 21:16:56" level=info msg="Running job node-density-heavy"
time="2023-03-22 22:33:38" level=fatal msg="Authorization error creating Deployment/postgres-1-30664: deployments.apps \"postgres-1-30664\" is forbidden: failed to get namespace: namespace \"node-density-heavy-30664\" not found"
```

```
$ ogns -o yaml node-density-heavy-30664 | grep creation
  creationTimestamp: "2023-03-22T22:33:37Z"
```

**Comment by afcollins** [comment]
Ok. Created, yes. Wondering if there's a check whether the namespace is Active before creating the objects.  I'm discarding server issues bc i've had other successful runs at this scale.

Looking for a safe-guard or at least a retry against what looks like a race condition.

**Comment by afcollins** [comment]
Looks like since it's an Authorization error, it doesn't get a retry. Can we allow a retry for authn errors?

https://github.com/cloud-bulldozer/kube-burner/blob/ad40e053d0c6d2db3346bb6349869d11f3e90092/pkg/burner/create.go#L223-L233

**Comment by rsevilla87** [comment]
Hey @afcollins , just merged  #280 that could fix the issue, I can create a new release for you if you want to test this asap.

**Comment by afcollins** [comment]
Ok, thanks! I can rebuild and give it a try. I applied a different fix.  I'll give it a shot.
https://github.com/cloud-bulldozer/kube-burner/commit/1fdbe6904d4ab4d8b243fd4bde90d3bb3d2b7d22

**Comment by afcollins** [comment]
Alright, I hit it with the #280 fix, so I think I am good. Thanks, Raúl!

```
time="2023-03-29 16:57:19" level=info msg="Running job node-density-heavy"
time="2023-03-29 18:01:25" level=error msg="Error creating object Deployment/postgres-1-25645 in namespace node-density-heavy-25645: deployments.apps \"postgres-1-25645\" is forbidden: failed to get namespace: namespace \"node-density-heavy-25645\" not found"
time="2023-03-29 18:01:25" level=error msg="Retrying object creation"
```
