### ISSUE TITLE
[BUG] cleanup timeout does not follow ocp --timeout argument

### ISSUE THREAD

**Issue by afcollins** [cloud-bulldozer/kube-burner#282]
**Output of `kube-burner `version**
```
$ ./bin/amd64/kube-burner version
Version: latest
Git Commit: c4b3281e0fe65b4d04a492cf0d77be76f4c5a731
Build Date: 2023-03-28-19:10:23
Go Version: go1.18.9
OS/Arch: linux amd64
```

**Describe the bug**
I ran a long run, and specifically set `--timeout 5h`, but the context times out during cleanup before 5h elapsed.

**To Reproduce**
```
$ ~/git/kube-burner/bin/amd64/kube-burner ocp node-density-heavy --timeout 5h --metrics-endpoint metrics-endpoint.yml --pods-per-node ... --es-index ... --es-server ...  2>&1 | tee -a kube-burner-$(date +"%F_%H-%M-%S")
```

**Expected behavior**
If workload scales up and garbage collects within 5 hours, there is no timeout.
If it exceeds 5h, the context may timeout.

**Screenshots or output**
Logs from kube-burner below.
The difference between 22:38:04 and 02:01:34 is only 3h23m30s.

```
time="2023-03-28 22:38:04" level=info msg="Listed nodes after using selector node-role.kubernetes.io/worker=,node-role.kubernetes.io/infra!=,node-role.kubernetes.io/workload!=: 26"
...
time="2023-03-29 00:46:36" level=info msg="Deleting namespaces with label kube-burner-uuid=bda02394-5c2e-404c-84d6-e5bbdcd9e920"
time="2023-03-29 01:13:30" level=info msg="Waiting for namespaces to be definitely deleted"
time="2023-03-29 02:01:34" level=fatal msg="Timeout cleaning up namespaces: Get \"https://api.test887.myocp4.com:6443/api/v1/namespaces?labelSelector=kube-burner-uuid%3Dbda02394-5c2e-404c-84d6-e5bbdcd9e920\": context deadline exceeded"
```

**Additional context**

**Comment by afcollins** [comment]
Ok. Thanks for pointing this out.  At the least, we could explain the timeout/4 as part of the timeout flag doc.

The simplest to me is to either use the same timeout for cleanup (i.e. timeout for benchmarking, timeout for GC).

What is intuitive for having a single value (to me, at least) is keeping the entire execution (benchmarking, index, GC) to the same timeout. So, if I set timeout=4h, then I expect kube-burner to terminate in 4h, regardless of where it is in the process.

I suppose introducing a new flag for GC timeout that defaults to timeout/4. Or maybe at the very least explaining this somewhere in the docs, even if it doesn't make it to the CLI help.

I have only hit this a few times ever. So now that I know how it works, I can set my `timeout` accordingly if I expect GC to take a certain amount of time.

**Comment by rsevilla87** [comment]
Fixed by https://github.com/cloud-bulldozer/kube-burner/pull/373
