### ISSUE TITLE
[RFE] preload uses node selectors specified

### ISSUE THREAD

**Issue by afcollins** [cloud-bulldozer/kube-burner#288]
**Is your feature request related to a problem? Please describe.**
If I specify node selectors for kube-burner to select certain nodes, I also want the capability for preload to use the same node selector. Currently, preload runs on all nodes of the cluster, which raises eyebrows with users looking to restrict the execution.

**Describe the solution you'd like**
I would like preload daemonset to be created with the node selector specified to kube-burner.

Or, as a stretch, to specify a node selector for kube-burner at the job or global level to apply to all workloads created within that group.

**Describe alternatives you've considered**
Exposing any node selectors to be templated into the workload manifests are at the config.jobs.objects level, but these have no influence on preload.

**Additional context**
The ability to run workloads comes from e2e-benchmarking, where the namespace label is exposed as a variable. I see that it is not exposed in the `kube-burner ocp` subcommand workloads, which assumes we are running on `node-role.kubernetes.io/worker` nodes.

**Comment by afcollins** [comment]
Capturing more detail here after chatting with Vishnu more about this yesterday.

Preload daemonset has node selectors hard-coded in go code, and no means of configuration override.

The ocp-wrapper also does not expose variables for node selector labels, however, one could achieve this by extracting the workload and modifying the configs with specific labels.

The larger ask here is to have the ability to override nodeSelectors for both preload and all workload pods.

The use case is a user who wants to be able to run on a subset of nodes in a cluster, without scheduling to any of the other nodes in the cluster. With the current setup, if I modify the workloads with specific labels, preload will still run on all role=worker nodes, which may not include the subset of nodes.

**Comment by vishnuchalla** [comment]
Added an option `preaLoadNodeLabels` at a job level to specify node selectors for preload resources. Keeping it at the lowest granular level possible to leave it with flexibility on specifying node selector options for mixed requirements. Feel free to let us know if you have any further questions. Thank you!

**Comment by vishnuchalla** [comment]
@afcollins Regarding your comment [here](https://github.com/cloud-bulldozer/kube-burner/pull/382#issuecomment-1640686866), I agree this is more of a tactical fix at a very lower granular level, but inserting node-labels through `GO` will make us move away from the current flexibility we have now in setting node-selector and affinity rules in the `YAML` configuration files. And on a side note, It requires a lot of code changes to add node-selector labels based on the resource types on the cluster and also will result in adding extra code which is very specific to this use case. Rather I would prefer to have them through resource `YAML` configuration files which is simple and can be written in our own desired way by adding either `node-selectors` or `affinity/antiaffinity` rules. I am open to other thoughts too. Thank you!

**Comment by afcollins** [comment]
That's fair. You convinced me. :)
