### ISSUE TITLE
[RFE] Autodiscover if a resource is namespaced or not

### ISSUE THREAD

**Issue by rsevilla87** [cloud-bulldozer/kube-burner#340]
**Is your feature request related to a problem? Please describe.**
The current logic requires to set the variable `namespaced` to true when we want kube-burner to treat a resource as namespaced. There're alternatives in where we can prescind of this variable.

**Describe the solution you'd like**
Make kube-burner able to find out if an object is namespaced or not.

**Describe alternatives you've considered**
Seems like the `RestMapping` object has a [method ](https://pkg.go.dev/k8s.io/apimachinery/pkg/api/meta#RESTScope) that provides such information

**Comment by darkmuggle** [comment]
Thank you for accepting my PR #338, and I agree that using the rest mapper is much cleaner so I took the liberty to tease it out.

**Comment by darkmuggle** [comment]
Actually, hold on this -- #333 is tangentially related, and show that a need for `isNamespaced` func.

**Comment by darkmuggle** [comment]
Okay, re-pushed -- I like this change a bit more. I'm happy to iterate on this to get it to align with the project's vision. I'm looking to use kube-burner for a project and am happy to contribute and make it better.
