### ISSUE TITLE
[BUG] iterationsPerNamespace not working with for node-density-cni-networkpolicy workload

### ISSUE THREAD

**Issue by venkataanil** [cloud-bulldozer/kube-burner#350]
I want to run node-density-cni-networkpolicy with "namespacedIterations" using e2e.

I have added "iterationsPerNamespace" in 
https://github.com/cloud-bulldozer/e2e-benchmarking/blob/master/workloads/kube-burner/workloads/node-density-cni-networkpolicy/node-density-cni-networkpolicy.yml
i.e
[root@vkommadi-dev kube-burner]# git diff workloads/node-density-cni-networkpolicy/node-density-cni-networkpolicy.yml
diff --git a/workloads/kube-burner/workloads/node-density-cni-networkpolicy/node-density-cni-networkpolicy.yml b/workloads/kube-burner/workloads/node-density-cni-networkpoli
index 293dc00..3ba77de 100644
--- a/workloads/kube-burner/workloads/node-density-cni-networkpolicy/node-density-cni-networkpolicy.yml
+++ b/workloads/kube-burner/workloads/node-density-cni-networkpolicy/node-density-cni-networkpolicy.yml
@@ -59,7 +59,8 @@ jobs:
     jobIterations: 1
     qps: 1
     burst: 1
-    namespacedIterations: false
+    namespacedIterations: true
+    iterationsPerNamespace: 1
     namespace: {{.UUID}}
     cleanup: {{.CLEANUP}}
     jobPause: 1m
@@ -72,7 +73,8 @@ jobs:
     jobIterations: {{.TEST_JOB_ITERATIONS}}
     qps: {{.QPS}}
     burst: {{.BURST}}
-    namespacedIterations: false
+    namespacedIterations: true
+    iterationsPerNamespace: 20
     namespace: {{.UUID}}
     podWait: {{.POD_WAIT}}
     cleanup: {{.CLEANUP}}

However while running the workload i.e 
cd /root/e2e-benchmarking/workloads/kube-burner
 LOG_LEVEL=debug PODS_PER_NODE=80 WORKLOAD=node-density-cni-networkpolicy ./run.sh

kube-burner is failing with below error
time="2023-06-12 15:31:05" level=info msg="🔥 Starting kube-burner (0.17.3@c38fe7eb37c62686b68e2b64bdc8311a4d73d8f1) with UUID 086705d7-fb98-4520-b003-b435e29f51be"
time="2023-06-12 15:31:05" level=fatal msg="Error decoding configuration file node-density-cni-networkpolicy.yml: yaml: unmarshal errors:\n  line 20: field iterationsPerNamespace not found in type config.rawJob\n  line 34: field iterationsPerNamespace not found in type config.rawJob"

Note: This is a 4 worker node self-managed AWS environment.

**Comment by afcollins** [comment]
iterationsPerNamespace were released in v1.6.
node-density-cni-networkpolicy also is not part of the ocp sub-command yet, so I will give an example with node-density-cni.

What you want to do from that release to set the field is:
1. Extract the job configs: `kube-burner ocp node-density-cni --extract`
2. Edit the extracted config `node-density-cni.yml` with the changes from #349
3. From the same directory, run the job via `kube-burner ocp node-density-cni <... any other flags you want to set ... > `

**Comment by venkataanil** [comment]
we need to enhance node-density-cni in kube-burner to accept network policies as an option

**Comment by vishnuchalla** [comment]
@venkataanil It looks like this issue is due to outdated version of kube-burner (which doesn't have iterationPerNamespace) in e2e. Apart from that, kube-burner does have support for deploying a networkpolicy as well. It has a GO [implementation](https://github.com/cloud-bulldozer/kube-burner/blob/master/pkg/burner/create.go#L244-L246) that is similar to `oc apply -f resource.yaml` which simply deploys the specified resource `YAML configuration` onto the cluster. I have cross verified it through kube-burner.
```
[vchalla@vchalla ~]$ oc describe netpol/allow-1-0
Name:         allow-1-0
Namespace:    kube-burner-test
Created on:   2023-07-18 22:18:28 -0400 EDT
Labels:       kube-burner-index=2
              kube-burner-job=node-density-cni-policy
              kube-burner-uuid=4df1df0a-9ec9-467d-a0e6-0e08b1e277dd
Annotations:  <none>
Spec:
  PodSelector:     name=webserver-1-0
  Allowing ingress traffic:
    To Port: 8080/TCP
    From: <any> (traffic not restricted by source)
  Not affecting egress traffic
  Policy Types: Ingress
```
So once you have the latest kube-burner version updated in e2e, you should be able to run your workload I believe. Please feel free to share if you have any further question/concerns on this. Thank you!

**Comment by venkataanil** [comment]
This is avaialable in latest kube-version version
