### ISSUE TITLE
[BUG] Glitch in current pod latencies being calculated.

### ISSUE THREAD

**Issue by vishnuchalla** [cloud-bulldozer/kube-burner#387]
# Bug Description
There seems to be a small glitch in current pod latencies being calculated.

## **Output of `kube-burner` version**
Version: latest
Git Commit: 8b56817e4e978dd8ae5b59e246a97b89539b4f6e
Build Date: 2023-07-20-22:19:24
Go Version: go1.20.4
OS/Arch: linux amd64

## **Describe the bug**

The way we currently calculate lantencies involves the below steps:
For creation time we listen for the creation event and then manually set a [timestamp](https://github.com/cloud-bulldozer/kube-burner/blob/master/pkg/measurements/pod_latency.go#L79) using `time.now()` (which has timestamp in milliseconds) and for the rest of the stages like scheduled, initialized, container-ready and pod-ready we collection the time stamps emitted by the pod [statuses](https://github.com/cloud-bulldozer/kube-burner/blob/master/pkg/measurements/pod_latency.go#L95-L116) (Times are only till seconds). At the end we calculate differences between them in milliseconds and declare it as latency.
```
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2023-07-15T23:45:46Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2023-07-17T19:27:07Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2023-07-17T19:27:07Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2023-07-15T23:45:46Z"
    status: "True"
    type: PodScheduled
```

## **To Reproduce**

1. Add these log statements [here](https://github.com/cloud-bulldozer/kube-burner/blob/master/pkg/measurements/pod_latency.go#L112).
```
log.Infof("Pod %+v creation time set by us: %+v", pm.Name, pm.Timestamp)
log.Infof("Pod %+v creation time set by us in unixmilli: %+v", pm.Name, pm.Timestamp.UnixMilli())
log.Infof("Pod %+v actual creation time: %+v", pod.Name, pod.CreationTimestamp.UTC())
log.Infof("Pod %+v actual creation time in unixmilli: %+v", pod.Name, pod.CreationTimestamp.UnixMilli())
pm.podReady = c.LastTransitionTime.Time.UTC()
log.Infof("Pod %+v captured PodReady Time: %+v", pm.Name, pm.podReady)
log.Infof("Pod %+v current pod ready latency: %+v", pm.Name, int(pm.podReady.Sub(pm.Timestamp).Milliseconds()))
log.Infof("Pod %+v actual pod ready latency: %+v", pm.Name, int(pm.podReady.Sub(pod.CreationTimestamp.UTC()).Milliseconds()))
log.Debugf("Pod %s is ready", pod.Name)
```
2. Build your own binary using `make build && sudo make install`
3. Run this command to come across the observations.
```
kube-burner ocp node-density-heavy --timeout 1h --metrics-endpoint ~/metrics-endpoints.yaml --pods-per-node=250 --log-level=debug --gc=true 2>&1 | tee -a kube-burner-$(date +"%F_%H-%M-%S")
```
And we should be able to see the currently obtained values and the actual values. Below is an example instance of a pod below.
```
time="2023-07-20 22:21:18" level=info msg="Pod postgres-1-4-c587bf657-j75wd creation time set by us: 2023-07-21 02:21:13.676526207 +0000 UTC" file="pod_latency.go:113"
time="2023-07-20 22:21:18" level=info msg="Pod postgres-1-4-c587bf657-j75wd creation time set by us in unixmilli: 1689906073676" file="pod_latency.go:114"
time="2023-07-20 22:21:18" level=info msg="Pod postgres-1-4-c587bf657-j75wd actual creation time: 2023-07-21 02:21:13 +0000 UTC" file="pod_latency.go:115"
time="2023-07-20 22:21:18" level=info msg="Pod postgres-1-4-c587bf657-j75wd actual creation time in unixmilli: 1689906073000" file="pod_latency.go:116"
time="2023-07-20 22:21:18" level=info msg="Pod postgres-1-4-c587bf657-j75wd captured PodReady Time: 2023-07-21 02:21:17 +0000 UTC" file="pod_latency.go:118"
time="2023-07-20 22:21:18" level=info msg="Pod postgres-1-4-c587bf657-j75wd current pod ready latency: 3323" file="pod_latency.go:119"
time="2023-07-20 22:21:18" level=info msg="Pod postgres-1-4-c587bf657-j75wd actual pod ready latency: 4000" file="pod_latency.go:120"
time="2023-07-20 22:21:18" level=debug msg="Pod postgres-1-4-c587bf657-j75wd is ready" file="pod_latency.go:121"
```
## **Expected behavior**
From the above log the actual pod ready latency is 4000 ms but we are getting 3323 ms, and if the same thing happens for all the pods (which is happening currently) in the workload, we will definitely see different numbers while calculating aggregates and quantiles.

So instead we should simply get all the timestamps from the pod statuses (including creation timestamp using `pod.CreationTimeStamp`) and calculate delta between them to get the latencies instead of manually setting the timestamps after listening to a watcher event as it is an API call and is expected to always add some extra delay. Open to other opinions too. Thank you!

## **Screenshots or output**
Full output log here: https://gist.github.com/vishnuchalla/bb371eaa7d691127bc17037bb3cc4de3

**Comment by rsevilla87** [comment]
I don't recall now, but for some reason I discarted using the pod's creationTimestamp, I think it wasn't working well at large scale.

**Comment by rsevilla87** [comment]
> mply get all the timestamps from the pod statuses (including creation timestamp using `pod.CreationTimeStamp`) and calculate delta between them to get the latencies instead of manually setting the

I don't understand this issue very well, In the current implementation:

- pod creation timestamp is set to the current timestamp when the pod is received by the watcher. I discarded using creationTimestamp because it doesn't provide milliseconds granularity. Also, when I coded this, I did lot of tests to ensure there wasn't a significant delay from the API event.
- The remaining stages: Scheduled, initialized and Ready. Are calculated after subtracting from their condition's timestamps the previous timestamp.

I don't fully understand the code snippet you pasted, can you provide more detail?

**Comment by vishnuchalla** [comment]
Yes, I have come across those resources, I agree that kubernetes currently emits those timestamps only up to seconds precision which is well known problem by design. But my concern here is on our own i.e `kube-burner's` methodology of calculating latencies. 

**Current Calculation Steps:**
Step 1: Creation time set by us on listening to a [creation event](https://github.com/cloud-bulldozer/kube-burner/blob/master/pkg/measurements/pod_latency.go#L79) using `time.now()` that has upto milliseconds precision: 
```
time="2023-07-20 22:21:22" level=info msg="Pod postgres-1-30-6785f545d6-qcsvd creation time set by us: 2023-07-21 02:21:17.019937259 +0000 UTC" file="pod_latency.go:113"
```
Step 2: Next we keep on listening to the [update events](https://github.com/cloud-bulldozer/kube-burner/blob/master/pkg/measurements/pod_latency.go#L114) and for each such event we record timestamps for other states like `scheduled`, `initialized`, `containersready` and `podready`  from the status emitted by the pod which only give us those latencies only upto seconds precision. And example instance of captured podready timestamp:
```
time="2023-07-20 22:21:22" level=info msg="Pod postgres-1-30-6785f545d6-qcsvd captured PodReady Time: 2023-07-21 02:21:22 +0000 UTC" file="pod_latency.go:118"
```
Step 3:
And the end we calculate the podReady latency by subtracting those two timestamps
```
m.PodReadyLatency = int(m.podReady.Sub(m.Timestamp).Milliseconds())
if m.PodReadyLatency < 0 {
	m.PodReadyLatency = 0
}
```
So, in summary creation timestamp is recorded with milliseconds precision (isn't read from pod status) and rest of the timestamps like `scheduled`, `initialized`, `containersReady` and `podReady` are recorded with seconds precision (read from pod status) which is a non-uniform way of collecting timestamps and using them for calculating latencies.

IMHO, in order to solve this problem we have two approaches
* We should either completely rely on listening to create/update events (using `client-go` library) and set the timestamps on our own upto milliseconds precision and use them for calculating latencies
OR
* We should get all the timestamps from the pod statuses which have support only till seconds precision and use them for calculating latencies, we can convert them to milliseconds  in order to be backward compatibility with our current data.

So, I would prefer to go with second approach, because listening to create/update events is done by `client-go` library which will add the extra latency for getting the response from server which might take a longer time sometimes (i.e request round-trip time) resulting in always recording a greater timestamp than actual. For example

```
time="2023-07-20 22:21:22" level=info msg="Pod postgres-1-30-6785f545d6-qcsvd creation time set by us: 2023-07-21 02:21:17.019937259 +0000 UTC" file="pod_latency.go:113"
time="2023-07-20 22:21:22" level=info msg="Pod postgres-1-30-6785f545d6-qcsvd creation time set by us in unixmilli: 1689906077019" file="pod_latency.go:114"
time="2023-07-20 22:21:22" level=info msg="Pod postgres-1-30-6785f545d6-qcsvd actual creation time: 2023-07-21 02:21:16 +0000 UTC" file="pod_latency.go:115"
time="2023-07-20 22:21:22" level=info msg="Pod postgres-1-30-6785f545d6-qcsvd actual creation time in unixmilli: 1689906076000" file="pod_latency.go:116"
time="2023-07-20 22:21:22" level=info msg="Pod postgres-1-30-6785f545d6-qcsvd captured PodReady Time: 2023-07-21 02:21:22 +0000 UTC" file="pod_latency.go:118"
time="2023-07-20 22:21:22" level=info msg="Pod postgres-1-30-6785f545d6-qcsvd current pod ready latency: 4980" file="pod_latency.go:119"
time="2023-07-20 22:21:22" level=info msg="Pod postgres-1-30-6785f545d6-qcsvd actual pod ready latency: 6000" file="pod_latency.go:120"
```
The actual podReady latency was `6000ms`, becuase of recording the creation timestamp manually as `2023-07-21 02:21:17.019937259 +0000 UTC` instead of the actual ones which is `2023-07-21 02:21:16 +0000 UTC` we are seeing an incorrect latency at the end as `4980ms` which almost has delta of `>1s` than the actual ones.

And also the [clusterloaderv2](https://github.com/kubernetes/perf-tests/blob/7bacdab9d634738d694240781c4e723256f0feb7/clusterloader2/pkg/measurement/common/slos/pod_startup_latency.go#L318) is also using `pod.CreationTimestamp.Time` to capture the creation time and they are keeping the latencies upto seconds [precision](https://github.com/kubernetes/perf-tests/blob/7bacdab9d634738d694240781c4e723256f0feb7/clusterloader2/pkg/measurement/common/slos/pod_startup_latency.go#L186).

And one more advantage of implementing on of the above approaches is we can avoid these `<0` checks [here](https://github.com/cloud-bulldozer/kube-burner/blob/master/pkg/measurements/pod_latency.go#L209) which are against the natural behavior of calculating the latencies.

**Comment by afcollins** [comment]
Great find, Vishnu!

The postgres discrepancy you highlighted (`2023-07-21 02:21:16 +0000 UTC` vs. `2023-07-21 02:21:17.019937259`) is indeed compelling evidence.

I prefer to have millisecond precision, but since the milliseconds are inaccurate then I don't think they provide much value.
Since they include the round trip time for the informer to report back to the client, it appears the milliseconds introduce some error to the measurement.

If we are able to add these "v2" values (calculated using creationTimestamp) to the existing podLatencyMeasurement, that would allow us to evaluate this change on the same set of pods (rather than comparing two different runs which would have different latencies).

I collect the p50, p99, and max Ready from the kube-burner log output, so if you log them there (still as milliseconds precision, so I don't have to transform existing data), that would be excellent.

If these v2 measurements are also indexed, I would use more in-depth analysis/histogramming through kibana/grafana to compare.

**Comment by vishnuchalla** [comment]
> Great find, Vishnu!
> 
> The postgres discrepancy you highlighted (`2023-07-21 02:21:16 +0000 UTC` vs. `2023-07-21 02:21:17.019937259`) is indeed compelling evidence.
> 
> I prefer to have millisecond precision, but since the milliseconds are inaccurate then I don't think they provide much value. Since they include the round trip time for the informer to report back to the client, it appears the milliseconds introduce some error to the measurement.
> 
> If we are able to add these "v2" values (calculated using creationTimestamp) to the existing podLatencyMeasurement, that would allow us to evaluate this change on the same set of pods (rather than comparing two different runs which would have different latencies).
> 
> I collect the p50, p99, and max Ready from the kube-burner log output, so if you log them there (still as milliseconds precision, so I don't have to transform existing data), that would be excellent.
> 
> If these v2 measurements are also indexed, I would use more in-depth analysis/histogramming through kibana/grafana to compare.

[PR](https://github.com/cloud-bulldozer/kube-burner/pull/388) ready for AB testing. No changes required in the current YAML files. Just a rebuild using `make build; sudo make install` and re-run should do the job and emit v2 latencies both in the logs as well as in the ES. Thank you!

**Comment by rsevilla87** [comment]
@vishnuchalla @afcollins , I think any of the approaches here discussed are not 100% correct. As I said using creationTimestamp is not accurate either, this value is rounded up or down by the apiserver and has second level precision, this approach comes with some tradeoffs:

- We will loose scheduling latency numbers. As this kind of event uses to take a few milliseconds
- We can deviate up to 1s from the actual event timestamp.
- Our baselines will be automatically invalidated

In addition. clusterloader2 uses a different strategy not only based on `creationTimestamp` as you mentioned. They are measuring different pod phases in a different way, summarizing them:

- create_to_schedule: timestamp when the scheduling event was seen minus `creationTimestamp`. [Reference](https://github.com/kubernetes/perf-tests/blob/master/clusterloader2/pkg/measurement/common/slos/pod_startup_latency.go#L279-L300). As I said this will be likely 0s as shows the snippet below, taken from a random Prow job I took a look

```shell
141] PodStartupLatency: 100 worst create_to_schedule latencies: [{test-zffjwq-2/scheduler-throughput-deployment-0-847cc9c46-rd64f 0s} {test-zffjwq-2/scheduler-throughput-deployment-0-847cc9c46-fr8l2 0s} {test-zffjwq-2/scheduler-throughput-deployment-0-847cc9c46-splbt 0s} {test-zffjwq-2/scheduler-throughput-deployment-0-847cc9c46-7d7p5 0s} {test-zffjwq-2/scheduler-throughput-deployment-0-847cc9c46-8cmp7 0s} {test-zffjwq-2/scheduler-throughput-deployment-0-847cc9c46-pcwn7 0s}
```

- schedule_to_run: Scheduled event time minus the result from [here](https://github.com/kubernetes/perf-tests/blob/master/clusterloader2/pkg/measurement/common/slos/pod_startup_latency.go#L321-L324) (which is normally set as StartedAt) Second precision
```
I0720 07:00:32.007547   17188 phase_latency.go:141] PodStartupLatency: 100 worst schedule_to_run latencies: [{test-zffjwq-2/scheduler-throughput-deployment-0-847cc9c46-7rnnp 2s} {test-zffjwq-2/scheduler-throughput-deployment-0-847cc9c46-9nxh7 2s} {test-zffjwq-
```
- run_to_watch: Delta between run timestamp (Pod's StartedAt) and workqueue's event time (This one also includes some of the API delay you mentioned) Millisecond precision
```
I0720 07:00:32.008216   17188 phase_latency.go:141] PodStartupLatency: 100 worst run_to_watch latencies: [{test-zffjwq-2/scheduler-throughput-deployment-0-847cc9c46-ztljr 1.678534221s} {test-zffjwq-2/scheduler-throughput-deployment-0-847cc9c46-slpr7 1.68103936s} Millisecond precision
```
- schedule_to_watch: Delta between scheduling timestamp and workqueue's event time. Millisecond precision
```
I0720 07:00:32.008813   17188 phase_latency.go:141] PodStartupLatency: 100 worst schedule_to_watch latencies: [{test-zffjwq-2/scheduler-throughput-deployment-0-847cc9c46-6qvfw 2.979608209s} {test-zffjwq-2/scheduler-throughput-deployment-0-847cc9c46-vrb24 2.980683893s} {test-zffjwq-2/scheduler-throughput-deployment-0-847cc9c46-mth9s 2.990902028s} {test-zffjwq-2/scheduler-throughput-deployment-0-847cc9c46-527k7 2.997246475s} {test-zffjwq-2/scheduler-throughput-deployment-0-847cc9c46-5wcmz 2.999922756s} {test-zffjwq
```
- pod_startup: Delta between creationTimestamp and workqueue's event time. Millisecond precision
```
I0720 07:00:32.009485   17188 phase_latency.go:141] PodStartupLatency: 100 worst pod_startup latencies: [{test-zffjwq-2/scheduler-throughput-deployment-0-847cc9c46-prb7v 3.019445144s} {test-zffjwq-2/scheduler-throughput-deployment-0-847cc9c46-nqpnq 3.019973576s}
```


As you can see the strategy we're following to measure the pod latencies is different from what is being used in k8s upstream, but as they said, it's not 100% . Our strategy is not 100% accurate either, but I think it has demonstrated to be stable enough to be trusted (This is what actually matters and not if the numbers are better or worse, we just need deterministic results to be able detect a performance degradation)

Honestly, I don't think we should change this code unless there's a proof these numbers don't have the enough quality to be trusted.

**Comment by vishnuchalla** [comment]
Yes @rsevilla87. I totally agree with your statement that we not 100% correct in either of the approaches. And I understand our interest in seeing those numbers in milliseconds precision, but our current approach looks like `we creating our own milliseconds when it is not actually offered by kubernertes`, which is adding the extra latency of request round trip time which is even going `> 1s` sometimes. Example instances are  `(2023-07-21 02:21:16 +0000 UTC vs. 2023-07-21 02:21:17.019937259)` and `(2023-07-21 02:21:39.050968336 +0000 UTC vs 2023-07-21 02:21:38 +0000 UTC)` etc in just a 3 worker node cluster, and might even go worse in a large cluster with larger loads expecially in cross-region calls (where every request has network latency + inter-continental trip time added as well) which will lead us to `0` latencies according to our current  logic missing actual numbers completely. So my only concern is `having something is better than nothing and also that something should be coming from official kubernetes upstream library but not from our custom logic to create those milliseconds`. And also the advantage of using client-go `CreationTimestamp.Unixmilli()` is, currently it has fields to store milliseconds but the value is not being populated as of now, for example `1689906098000` those last 3 zeros are to store milliseconds precision but not being populated. And in future once the change is made in the upstream, we will automatically start seeing the `milliseconds` being populated without any code changes from our side, on the other hand, if we keep our current logic to have our custom calculation for milliseconds,  we might be missing that update and might be staying out of the trend. 

So my suggestion is not to be make the change immediately, but it is worth giving a try on this to perform an alpha-beta feature testing to understand its reliability. Because,
* All the 0's that we are seeing in our current latencies are not actually 0's and
* And every latency number has those extra milliseconds that include some error (due to request round trip time).

**Comment by vishnuchalla** [comment]
Or else I have an alternative approach, to avoid those `>1s` deltas and `0`'s preserving the milliseconds with our current logic. It would be a mixture of my suggestion and the current logic but will still have a minimal error rate. Below is the algorithm for it

**Step 1:**
We will capture timestamp from both statuses and live create/update events.
Time stamps captured from watcher events(using time.now() has milliseconds precision):
```
  * creation_timestamp_live: "2023-07-15 23:45:46.0123"
  * scheduled_timestamp_live: "2023-07-15 23:45:46.423"
  * initialized_timestamp_live: "2023-07-15 23:45:46.412"
  * containersReady_timestamp_live: "2023-07-17 19:27:07.532"
  * podReady_timestamp_live: "2023-07-24 08:45:52.532"
```
Time stamps captured from status (has seconds precision):
```  
  * creation_timestamp_status: "2023-07-15 23:45:46 +0000 UTC"
  * scheduled_timestamp_status: "2023-07-15 23:45:46 +0000 UTC"
  * initialized_timestamp_status: "2023-07-15 23:45:46 +0000 UTC"
  * containersReady_timestamp_status: "2023-07-17 19:27:07 +0000 UTC"
  * podReady_timestamp_status: "2023-07-24 08:45:51 +0000 UTC"
```

**Step 2:** 
Check if any of the live captured timestamps have a delta `>1s` with its corresponding version that is captured from pod status. If yes, simply update that corresponding time stamp with the ones captured from pod status.
```
if (creation_timestamp_live - creation_timestamp_status) >= 1s:
    creation_timestamp = creation_timestamp_status
if (scheduled_timestamp_live - scheduled_timestamp_status) >= 1s:
    scheduled_timestamp = scheduled_timestamp_status
if (initialized_timestamp_live - initialized_timestamp_status) >= 1s:
    initialized_timestamp = initialized_timestamp_status
if (containersReady_timestamp_live - containersReady_timestamp_status) >= 1s:
    containersReady_timestamp = containersReady_timestamp_status
if (podReady_timestamp_live - podReady_timestamp_status) >= 1s:
    podReady_timestamp = podReady_timestamp_status
```

**Step 3:** 
Finally we can use the same existing math to calculate the latencies with a slight modification as below.
```
m.ContainersReadyLatency = int(containersReady_timestamp.Sub(creation_timestamp).Milliseconds())
if m.ContainersReadyLatency < 0 {
	m.ContainersReadyLatency =  int(containersReady_timestamp.Sub(creation_timestamp_status).Milliseconds())
}
m.SchedulingLatency = int(scheduled_timestamp.Sub(creation_timestamp).Milliseconds())
if m.SchedulingLatency < 0 {
	m.SchedulingLatency = int(scheduled_timestamp.Sub(creation_timestamp_status).Milliseconds())
}
m.InitializedLatency = int(initialized_timestamp.Sub(creation_timestamp).Milliseconds())
if m.InitializedLatency < 0 {
	m.InitializedLatency = int(initialized_timestamp.Sub(creation_timestamp_status).Milliseconds())
}
m.PodReadyLatency = int(podReady_timestamp.Sub(creation_timestamp).Milliseconds())
if m.PodReadyLatency < 0 {
	m.PodReadyLatency = int(podReady_timestamp.Sub(creation_timestamp_status).Milliseconds())
}
```

This approach will solve my major concerns about those `>1s` deltas and those unwanted `0`'s, but still there will be some error which will anyways be in any other approach we choose. Open to others thoughts too!

cc: @rsevilla87 @afcollins

**Comment by mohit-sheth** [comment]
- We can document our process to calculate pod-latency.
- We can add why we do not currently use pod.CreationTimeStamp and instead prefer time.now
- We can also specify +- 1 second as our range for latency

_Thinking out loud
We can switch between v1 and v2 based on how much the delta is_

**Comment by vishnuchalla** [comment]
Added a comment on top of our latency calculations about the delays in the mentioned [PR](https://github.com/cloud-bulldozer/kube-burner/pull/388). Few gists: [gist1](https://gist.github.com/vishnuchalla/f2aef188eebdbbc04150ec2b08bd6315) and [gist2](https://gist.github.com/vishnuchalla/ce806fd2a8c808026dc88a210ae4328d) for the record that has seconds of delays while capturing `creationTimestamp` with a maximum value seen upto `4.431` seconds so far.

**Comment by vishnuchalla** [comment]
Closing for now, as we have V2 changes merged.

**Comment by vishnuchalla** [comment]
Reopening this issue as a tracker to make note of any unusual latency values reported by users.
