### ISSUE TITLE
[RFE] Verify if container registry is up & running prior running a workload with builds

### ISSUE THREAD

**Issue by rsevilla87** [cloud-bulldozer/kube-burner#389]
**Is your feature request related to a problem? Please describe.**

It would be a nice feature to provide kube-burner the ability to verify if the internal container registry is up and running in the cluster under test.

**Describe the solution you'd like**

This feature should only affect the OCP wrapper, since it's mainly OpenShift related, just a simple check to query the image-registry cluster operator object to determine if it's ready or not should be enough, I wouldn't verify if it's working well or not for the sake of complexity.

```yaml
$ oc get co image-registry -o yaml
apiVersion: config.openshift.io/v1
kind: ClusterOperator
metadata:
  creationTimestamp: "2021-01-14T01:23:28Z"
  generation: 1
  name: image-registry
  resourceVersion: "426078413"
  uid: 01fb7ec0-6a44-4c68-bda0-68b606c476ac
spec: {}
status:
  conditions:
  - lastTransitionTime: "2021-01-14T02:07:15Z"
    message: |-
      Available: The registry is ready
      NodeCADaemonAvailable: The daemon set node-ca has available replicas
      ImagePrunerAvailable: Pruner CronJob has been created
    reason: Ready
    status: "True"
    type: Available
  - lastTransitionTime: "2023-07-12T10:19:19Z"
    message: |-
      Progressing: The registry is ready
      NodeCADaemonProgressing: The daemon set node-ca is deployed
    reason: Ready
    status: "False"
    type: Progressing
  - lastTransitionTime: "2023-06-15T11:53:08Z"
    reason: AsExpected
    status: "False"
    type: Degraded
```

**Additional context**
In some platforms, like bare metal for example, the internal registry is not configured by default, and running a cluster-density workload would fail without it. Having the ability of reporting if the container registry is up & running prior running the workload would provide a useful information to the user.

**Comment by sferlin** [comment]
@akrzos : When this RFE is part of a new kube-burner release [1], we should update the version installed by jetlag (currently v1.3). I will monitor this in any case, this is just fyi.

[1]: https://github.com/cloud-bulldozer/kube-burner/releases

**Comment by vishnuchalla** [comment]
Closing it as the PR related to this specific RFE is merged.
