### ISSUE TITLE
[RFE] Run local index on kube-burner failure

### ISSUE THREAD

**Issue by afcollins** [cloud-bulldozer/kube-burner#403]
**Is your feature request related to a problem? Please describe.**
A kube-burner job can fail for any number of reasons. When a job fails, all pod measurements and data are lost.  This can be frustrating when the data from the failed run may hold some value in finding the root cause of the test failure.

**Describe the solution you'd like**
I would like improved error handling, such that regardless of why the create job might fail (expected error like a timeout, or unexpected errors), pod measurements and metrics profiles are still created and indexed (at least) locally.

Whether indexing needs to happen remotely, I am not sure. I think local indexing would be helpful for other tooling (e.g. prow) to backup the measurements/metrics for offline analysis while keeping this bad data out of the growing elastic/opensearch systems.

**Comment by vishnuchalla** [comment]
Closing this issue as a related PR: https://github.com/cloud-bulldozer/kube-burner/pull/441 is merged.
