### ISSUE TITLE
[RFE] Remove default pod-ready-latency=5s for ocp node-density

### ISSUE THREAD

**Issue by afcollins** [cloud-bulldozer/kube-burner#424]
**Is your feature request related to a problem? Please describe.**

--pod-ready-latency is a feature, but not all environments will actually meet the p99 < 5s latency that is the default `kube-burner ocp node-density`.

I see failures in runs all over (i.e. QE CI, airflow playground, airflow CPT) that should proceed forward instead of halting the entire test flow because p99 was higher than this arbitrary value.

Also, latest 4.14 nightlies p99s are well above 5s, so I think we need to reconsider how we use this value.

**Describe the solution you'd like**
Keep the flag. Remove the default value. It's a step towards a "more friendly to newcomers" user experience.

**Describe alternatives you've considered**
I could set the latency explicitly if I understand what a reasonable value is, but a user may not always know.

**Comment by smalleni** [comment]
> **Is your feature request related to a problem? Please describe.**
> 
> --pod-ready-latency is a feature, but not all environments will actually meet the p99 < 5s latency that is the default `kube-burner ocp node-density`.
> 
> I see failures in runs all over (i.e. QE CI, airflow playground, airflow CPT) that should proceed forward instead of halting the entire test flow because p99 was higher than this arbitrary value.
> 
> Also, latest 4.14 nightlies p99s are well above 5s, so I think we need to reconsider how we use this value.
> 
> **Describe the solution you'd like** Keep the flag. Remove the default value. It's a step towards a "more friendly to newcomers" user experience.
> 
> **Describe alternatives you've considered** I could set the latency explicitly if I understand what a reasonable value is, but a user may not always know.

Does kube-burner return an error exit code when the latency threshold is not met? Also, P99s with OCP 4.14 being above 5s is that at 250 nodes? I don't recall seeing anywhere close to 5s at 120 nodes from Anil's data,

**Comment by afcollins** [comment]
Kube-burner exits with a code, yes, so airflow doesn't proceed through the remaining benchmarks.

It is not limited to high node counts. Past two 4.14-aws-ovn-small airflow runs failed bc of threshold, and we're now missing other results after them in the DAG.

```
1f1d051a-node-density-20230809
[2023-08-09, 12:50:46 UTC] {subprocess.py:93} INFO - time="2023-08-09 12:50:46" level=info msg="node-density: Ready 50th: 1294 99th: 10542 max: 14945 avg: 2171" file="pod_latency.go:174"

463e4847-node-density-20230816
[2023-08-16, 12:55:52 UTC] {subprocess.py:93} INFO - time="2023-08-16 12:55:52" level=info msg="node-density: Ready 50th: 1333 99th: 12781 max: 21383 avg: 2325" file="pod_latency.go:176"
```
