### ISSUE TITLE
[RFE] Add storage contol plane related scenarios to ocp wrapper

### ISSUE THREAD

**Issue by smalleni** [cloud-bulldozer/kube-burner#427]
**Is your feature request related to a problem? Please describe.**

It would be good to have some scenarios that create PVCs, bind them to PVs, mount them in pods and finally reclaim them.

**Describe the solution you'd like**

PV/PVC related scenarios on OCP wrapper with appropriate checks that a storageclass exists in case dynamic provisioning is reqired.

**Describe alternatives you've considered**

**Additional context**

**Comment by smalleni** [comment]
Related to https://github.com/cloud-bulldozer/kube-burner/issues/426

**Comment by mfleader** [comment]
Can you define what you mean by scenario?

**Comment by afcollins** [comment]
@mfleader "scenario" just a generic term for a new workload. Like one alongside those here: https://github.com/cloud-bulldozer/kube-burner/tree/master/cmd/kube-burner/ocp-config

**Comment by mfleader** [comment]
Do the pods exist before the scenario starts?

From my initial work, it seems like you cannot mount a pvc volume by patching an existing pod.

**Comment by afcollins** [comment]
No. Think of it as you will create everything for the workload. Attaching a volume to an existing pod isn't a valid use case. Usually, you create PV/PVC first, then pod next and the pod mounts the volume.

Since we're interested in dynamic provisioning here, then we only need to create the PVCs and not the PVs. Maybe you'll have to create a StorageClass that supports dynamic provisioning. You'll have to do that analysis.

**Comment by mfleader** [comment]
Should this create a bunch of PVCs and Pods (like 100 each), and then reclaim the PVC and delete the Pod, or should it create 1 each and then reclaim and delete them over N iterations?

**Comment by afcollins** [comment]
Our current workloads create everything and take measurements to measure the scaleup, then delete as an unmeasured "garbage collection", but we are working towards measuring GC as well.

If you simply follow that pattern, then we can compare the added effect/overhead of PVC mounting on top of what we already understand reasonably well (e.g. node-density with added PVC).

Usually creating a single pod doesn't consume enough resources for us to measure, but we could achieve that by using churn. It could be a second phase to figure out whether churn is beneficial here and what settings to use.

**Comment by mfleader** [comment]
Should this live in `cmd/kube-burner/ocp-config` or in a different directory?

**Comment by afcollins** [comment]
Yes: "PV/PVC related scenarios on OCP wrapper ..."

**Comment by mfleader** [comment]
How do you do dynamic storage provisioning for a KinD cluster? 

The obvious provisioners seem to be these OpenShift [plugins for these platforms](https://docs.openshift.com/container-platform/4.13/storage/dynamic-provisioning.html#available-plug-ins_dynamic-provisioning).

**Comment by mfleader** [comment]
How do the other workloads 'scale'?

**Comment by mfleader** [comment]
How are the labels supposed to be specified?

**Comment by mfleader** [comment]
How do you verify the count of objects that have been created?

**Comment by vishnuchalla** [comment]
> With regards to potential dynamic storage provisioners, the obvious ones seem to be these OpenShift [plugins for these platforms](https://docs.openshift.com/container-platform/4.13/storage/dynamic-provisioning.html#available-plug-ins_dynamic-provisioning).
> 
> Are there other platforms that we want to test that would need a dynamic storage provisioner not already available as one of the above plugins?

These seem to be a good enough and handful of provisioners as a part of our workload. And also I like [this](https://github.com/cloud-bulldozer/kube-burner/pull/465/files#diff-6afc2d1a6a1ebb3ed1637263a6af8089f1870b4d809ffc5e4539e13c4e3b2d34R7) idea of parameterizing the `STORAGE_PROVISIONER` with a flexibility for user to specify it based on their requirements and infra.

**Comment by vishnuchalla** [comment]
> How do the other workloads 'scale'?

https://github.com/cloud-bulldozer/kube-burner/blob/master/pkg/burner/create.go#L200

**Comment by vishnuchalla** [comment]
> How are the labels supposed to be specified?

https://github.com/cloud-bulldozer/kube-burner/blob/master/pkg/burner/create.go#L207

**Comment by vishnuchalla** [comment]
> How do you verify the count of objects that have been created?

https://github.com/cloud-bulldozer/kube-burner/blob/master/pkg/burner/utils.go#L82

**Comment by vishnuchalla** [comment]
Regarding mechanics and working of other workloads, I would suggest to explore the codebase and play around with it on a cluster to understand the common patterns and functionality across workloads/jobs. This is not something one could entirely help others with, requires some own research. 

Docs: https://cloud-bulldozer.github.io/kube-burner/v1.7.8/

**Comment by mfleader** [comment]
I feel like we might care about the PVC claim size to cluster/node total, or free, storage size ratio, but I'm unsure how to implement that currently.

**Comment by vishnuchalla** [comment]
Yes, its good to set a smaller value as default and expose claim size as configurable option to the end user. I see [current value](https://github.com/cloud-bulldozer/kube-burner/pull/465/files#diff-8275cad9bcffd35ad7a6d0aa0b68e6105b248a44709ca93d660b49345eb37581R12) is being set to `1GB` which is too high.
cc: @afcollins
