### ISSUE TITLE
[RFE] Scrape metrics during clean up phase as well 

### ISSUE THREAD

**Issue by smalleni** [cloud-bulldozer/kube-burner#444]
**Is your feature request related to a problem? Please describe.**
Currently the metrics that are scraped and index for a create job even with cleanup set to true do not include the metrics for the duration of the cleanup. We do notice excessive resource usage during cleanup (gc) and would like to be able to keep track of it. 

**Describe the solution you'd like**
We could perhaps still do this today by having separate jobs for create (gc set to false) and delete, however we would like thsi functionality to work even with the ocp wrapper which means the scraping of metrics for the timestamp of the test should happen after cleanup.

**Describe alternatives you've considered**

**Additional context**

**Comment by Noreen21** [comment]
While it would be good to be able to measure resource usage during workload creation and deletion to capture any peaks, I believe that a better implementation strategy would be an option to exclude or include metrics from these phases, possibly through the introduction of a command line argument or something similar for the ocp wrapper. This way we are not enabling metric scraping for these phases by default and are still allowing for an option of capturing metrics only for the steady workload phase (which is of interest for Far Edge use case, for instance)
