### ISSUE TITLE
[BUG] index misses measurement at end time if it does not fall on an index step

### ISSUE THREAD

**Issue by afcollins** [cloud-bulldozer/kube-burner#455]
# Bug Description

When metrics are scraped from prometheus, they are not scraped from the timestamp when the job completes.

## **Output of `kube-burner` version**
```
Version: 1.7.6
Git Commit: 3993bf5abd2bb1ba0166e32dcd65d87b4506c928
Build Date: 2023-08-28T12:29:34Z
Go Version: go1.19.12
OS/Arch: linux amd64
```

## **Describe the bug**

I noticed when kube-burner indexes metrics, the final measurement is at a 30s step from the start timestamp, but the actual end timestamp is not collected.

## **To Reproduce**

1. Run kube-burner, indexing metrics.
1. Compare the timestamp of the final measurement reading and the ending timestamp (kube-burner output "Job took XmYs")

Actual output:

```
# kube-burner index -u $URL -t $TOKEN --start 1693584547 --end 1693584835
time="2023-09-01 21:04:22" level=info msg="🔍 Scraping prometheus metrics for benchmark from 2023-09-01T16:09:07Z to 2023-09-01T16:13:55Z" file="prometheus.go:66"
time="2023-09-01 21:04:22" level=info msg="File collected-metrics/nodeCPUSeconds-Workers.json created with 80 documents" file="prometheus.go:105"

# cat collected-metrics/nodeCPUSeconds-Workers.json | jq ' .[] | .timestamp ' | sort | uniq | tail
"2023-09-01T16:09:07Z"
"2023-09-01T16:09:37Z"
"2023-09-01T16:10:07Z"
"2023-09-01T16:10:37Z"
"2023-09-01T16:11:07Z"
"2023-09-01T16:11:37Z"
"2023-09-01T16:12:07Z"
"2023-09-01T16:12:37Z"
"2023-09-01T16:13:07Z"
"2023-09-01T16:13:37Z"

# cat collected-metrics/nodeCPUSecondsEnd-Workers.json | jq ' .[] | .timestamp ' | sort | uniq | tail
"2023-09-01T16:13:55Z"

```

Kube-burner knows what the end timestamp is (2023-09-01T16:13:55Z), but the last timestamp collected from the range query is 2023-09-01T16:13:37Z, while an 'instant' measurement using `@end()` gives the correct timestamp.

## **Expected behavior**

Range queries include metrics _at_ the ending timestamp of the range, regardless of the step interval requested.

This specific metric is sensitive enough that this would throw off comparison results.

## **Additional context**

See PR #454 for metrics profile, but 454 is _not_ the fix for this bug.

**Comment by afcollins** [comment]
Occurred to me that the "bug" (as I see it) could be in many of the layers involved in making a query. So, whether the fix is in kube-burner or in go-commons/prometheus, the solution I am thinking of is (roughly):

```
QueryRange {
...
  	r := apiv1.Range{Start: start, End: end, Step: step}
	v, _, err := p.api.QueryRange(context.TODO(), query, r)
	vEnd, _, err := p.api.Query(context.TODO(), query, end)
        v.append(vEnd)
...
}

**Comment by vishnuchalla** [comment]
I just did some analysis on the same and understood that if step is lesser than workload `diff(end-start)` in a range query all the metrics are being calculated using the start time. An example instance here
```
time="2023-09-28 16:26:05" level=debug msg="Range query: (sum(irate(node_cpu_seconds_total[2m])) by (mode,instance) and on (instance) label_replace(kube_node_role{role=\"worker\"}, \"instance\", \"$1\", \"node\", \"(.+)\")) > 0" file="prometheus.go:89"
time="2023-09-28 16:26:05" level=info msg="Deleting namespaces with label kube-burner-uuid=5385e787-8e81-491b-aca5-cd8068e8bc27" file="namespaces.go:64"
Matrix metric recorded start timestamp:  2023-09-28 20:25:58.320802324 +0000 UTC
Matrix metric recorded end timestamp:  2023-09-28 20:26:05.65333223 +0000 UTC
Matrix step was:  30s
Matrix metric timestamp: 2023-09-28 20:25:58.321 +0000 UTC
Matrix metric value: 15.125333333356929
Matrix metric timestamp: 2023-09-28 20:25:58.321 +0000 UTC
Matrix metric value: 0.001999999999998181
Matrix metric timestamp: 2023-09-28 20:25:58.321 +0000 UTC
Matrix metric value: 0.02800000000000485
Matrix metric timestamp: 2023-09-28 20:25:58.321 +0000 UTC
Matrix metric value: 0.013333333333290894
Matrix metric timestamp: 2023-09-28 20:25:58.321 +0000 UTC
Matrix metric value: 1.1206666666669964
Matrix metric timestamp: 2023-09-28 20:25:58.321 +0000 UTC
Matrix metric value: 2.213999999999457
```
since the difference between start and end is less than 30s we missed on the metrics on the end timestamp and only collected metrics based on the start time. So a simpler solution i can think of as of now is, when a `step < diff(end-start)` simply modify the `step=diff(end-start)` at the runtime as step is `time.Duration` type variable which should give us all the desired values. cc @afcollins @rsevilla87

**Comment by vishnuchalla** [comment]
And for the instant queries I experimented specifying two types to kube-burner
```
- query: sum( node_cpu_seconds_total and on (instance) label_replace(kube_node_role{role="worker",role!="infra"}, "instance", "$1", "node", "(.+)") ) by (mode)
  metricName: nodeCPUSecondsEnd-Workers-workload-end
  instant: true
```
Results:
```
time="2023-09-28 16:29:17" level=debug msg="Instant query: sum( node_cpu_seconds_total and on (instance) label_replace(kube_node_role{role=\"worker\",role!=\"infra\"}, \"instance\", \"$1\", \"node\", \"(.+)\") ) by (mode)" file="prometheus.go:79"
time="2023-09-28 16:29:17" level=info msg="Deleting namespaces with label kube-burner-uuid=43cb1c5e-39c3-447c-852e-433971c3a81e" file="namespaces.go:64"
Vector metric recorded end timestamp:  2023-09-28 20:29:17.631000859 +0000 UTC
Vector metric timestamp: 2023-09-28 20:29:17.631 +0000 UTC
Vector metric value: 73096988.71000001
Vector metric timestamp: 2023-09-28 20:29:17.631 +0000 UTC
Vector metric value: 105680.53999999998
Vector metric timestamp: 2023-09-28 20:29:17.631 +0000 UTC
Vector metric value: 218050.79000000004
Vector metric timestamp: 2023-09-28 20:29:17.631 +0000 UTC
Vector metric value: 15795.129999999996
Vector metric timestamp: 2023-09-28 20:29:17.631 +0000 UTC
Vector metric value: 253192.27
Vector metric timestamp: 2023-09-28 20:29:17.631 +0000 UTC
Vector metric value: 2156.5499999999997
Vector metric timestamp: 2023-09-28 20:29:17.631 +0000 UTC
Vector metric value: 815939.9800000001
Vector metric timestamp: 2023-09-28 20:29:17.631 +0000 UTC
Vector metric value: 2894532.2799999993
```

AND

```
- query: sum( node_cpu_seconds_total @end() and on (instance) label_replace(kube_node_role{role="worker",role!="infra"}, "instance", "$1", "node", "(.+)") ) by (mode)
  metricName: nodeCPUSecondsEnd-Workers-explicit-end
  instant: true
```
Results:
```
time="2023-09-28 16:29:18" level=debug msg="Instant query: sum( node_cpu_seconds_total @end() and on (instance) label_replace(kube_node_role{role=\"worker\",role!=\"infra\"}, \"instance\", \"$1\", \"node\", \"(.+)\") ) by (mode)" file="prometheus.go:79"
Vector metric recorded end timestamp:  2023-09-28 20:29:17.631000859 +0000 UTC
Vector metric timestamp: 2023-09-28 20:29:17.631 +0000 UTC
Vector metric value: 73096988.71000001
Vector metric timestamp: 2023-09-28 20:29:17.631 +0000 UTC
Vector metric value: 105680.53999999998
Vector metric timestamp: 2023-09-28 20:29:17.631 +0000 UTC
Vector metric value: 218050.79000000004
Vector metric timestamp: 2023-09-28 20:29:17.631 +0000 UTC
Vector metric value: 15795.129999999996
Vector metric timestamp: 2023-09-28 20:29:17.631 +0000 UTC
Vector metric value: 253192.27
Vector metric timestamp: 2023-09-28 20:29:17.631 +0000 UTC
Vector metric value: 2156.5499999999997
Vector metric timestamp: 2023-09-28 20:29:17.631 +0000 UTC
Vector metric value: 815939.9800000001
Vector metric timestamp: 2023-09-28 20:29:17.631 +0000 UTC
Vector metric value: 2894532.2799999993

```
They both gave us the exact same results as they considered workload end timestamp that is recorded by kube-burner at the end of its [execution](https://github.com/cloud-bulldozer/kube-burner/blob/master/pkg/prometheus/prometheus.go#L80). So feeding a query with `@end()` in kube-burner metrics profile doesn't seem to be adding any value. But when ran an instant query, if we want to capture instant prom query results for both start and end timestamps of a workload, we can definitely think of that.

**Comment by rsevilla87** [comment]
Can we just add the step size to the end timestamp? that should fix all the scenarios and doesn't require extra logic

**Comment by afcollins** [comment]
> So feeding a query with @end() in kube-burner metrics profile doesn't seem to be adding any value.

Repeat the queries instead using `@start()` and see that when you run it as an instant, you get the same value as `@end()` as opposed to when you run it as a range, you actually get the value at `@start()`

**Comment by afcollins** [comment]
>can we just add the step size to the end timestamp for the index subcommand?

No. That doesn't help when I want a metric at an exact timestamp, which is what I am asking about here.

**Comment by afcollins** [comment]
> when a step > diff(end-start) simply modify the step=diff(end-start) at the program runtime

I do agree with this, but I think most of the runs outside our tiny/local testing runs it won't be an issue.

It is not the solution I was looking for here, but we might achieve it IF we dynamically calculate "step" using start and end timestamps to ensure
1) minimum # of data points - Graphs do look strange when there are only 1-2 data points, and 
2) that the end timestamp will be included as a measurement.

Any solution that doesn't result in getting a metric at the end timestamp isn't the right solution to close this issue.

**Comment by vishnuchalla** [comment]
### Instant query API method
```
v, _, err := p.api.Query(context.TODO(), query, time)
```
So when given a query as instant, we have this compulsion as shown in the above snippet to specify a timestamp `time` on an instant query  from GO API. So recommendation is to use only queries that give us a single data-point  in case of an instant query. If planning to use timeSeries query as instant it is user's responsibility to specify either a @start() or @end() so that they fetch only a single data point. (We can add a note about this in docs)

### Range query API method
```
v, _, err := p.api.QueryRange(context.TODO(), query, step)
```
One more observation here, when we run a range query there are chances that we get missed on the end timestamp metric but we never miss on the start time metric.
```
Matrix metric recorded start timestamp:  2023-09-29 20:48:08.938957366 +0000 UTC
Matrix metric recorded end timestamp:  2023-09-29 20:48:14.592208601 +0000 UTC
Matrix step was:  1s
Matrix metric timestamp: 2023-09-29 20:48:08.939 +0000 UTC
Matrix metric value: 15.331999999983239
Matrix metric timestamp: 2023-09-29 20:48:09.939 +0000 UTC
Matrix metric value: 15.331999999983239
```
So I think its better to keep the `step` param exposed as is and adjust it accordingly instead of using `minimum # of data points`, because both have their own drawbacks. if step size is big we will see 1 datapoint within in a given interval (i.e at start timestamp only) and when it comes to `minimum # of data points` if the workload execution time is very short and if we manage to adjust step size accordingly at runtime, we might see many datapoints for that short period or else sometimes we might not see any datapoints and errors. Because if an interval is too short and the `minimum # of data points` is high step size will go close to zero while adjusting it, which will result in an error by prom. i.e
```
time="2023-09-29 17:43:59" level=warning msg="Error found with query (sum(irate(node_cpu_seconds_total[2m])) by (mode,instance) and on (instance) label_replace(kube_node_role{role=\"worker\"}, \"instance\", \"$1\", \"node\", \"(.+)\")) > 0: bad_data: invalid parameter \"step\": zero or negative query resolution step widths are not accepted. Try a positive integer" file="prometheus.go:92"
```

**Comment by vishnuchalla** [comment]
### Step size adjustment logic.
If step size doesn't properly divide an interval (i.e leaving that end timestamp), we can take the `gcd(step_size, diff(end-start))` which will give us a number (i.e new step size always >= 1) that perfectly divides the interval. And in case of intervals with <1s lets simply assign `step=diff(end-start)`.

With this approach we will be able to fetch metrics at start, end and at the configured steps in between in a given time-series query.

Any thoughts on this approach? @afcollins @rsevilla87

**Comment by afcollins** [comment]
> If planning to use timeSeries query as instant it is user's responsibility to specify either a @start() or @EnD() so that they fetch only a single data point. (We can add a note about this in docs)

`instant` doesn't give the right value with `@start()` because the Query argument is [hard-coded](https://github.com/cloud-bulldozer/kube-burner/blob/master/pkg/prometheus/prometheus.go#L80) to `end`.  You will see what I mean when you verify this behavior.

> we can take the gcd ...

I am OK with that, but it seems more complicated than making an extra Query at the end timestamp and merging it with the QueryRange results (that omits the end timestamp when it doesn't align with the step interval).

I also fear we are getting lost in the solution without understanding the requirements. There is one here, that I am calling a bug:
1) Range queries do not capture metrics AT (exactly) end timestamp (if end timestamp doesn't align with a step interval from the start timestamp).

I guess the other things I am asking for is an RFE, which is

2) to allow more options for instant queries to replace the currently hard-coded end timestamp, such that I can pick from: jobStart or jobEnd.  With the refactor of cleanup measurements, I think it would suffice to have those two options that would capture at both ends of scaleup and both ends of scaledown.

**Comment by vishnuchalla** [comment]
Appending my observation on @start() and @end() as well.
```
time="2023-09-29 19:02:40" level=debug msg="Instant query: sum( node_cpu_seconds_total @end() and on (instance) label_replace(kube_node_role{role=\"worker\",role!=\"infra\"}, \"instance\", \"$1\", \"node\", \"(.+)\") ) by (mode)" file="prometheus.go:79"
Vector metric recorded end timestamp:  2023-09-29 23:02:40.458525025 +0000 UTC
Vector metric timestamp: 2023-09-29 23:02:40.459 +0000 UTC
Vector metric value: 76780773.66000001
Vector metric timestamp: 2023-09-29 23:02:40.459 +0000 UTC
Vector metric value: 109080.63000000002
Vector metric timestamp: 2023-09-29 23:02:40.459 +0000 UTC
Vector metric value: 270684.79000000004
Vector metric timestamp: 2023-09-29 23:02:40.459 +0000 UTC
Vector metric value: 15795.739999999996
Vector metric timestamp: 2023-09-29 23:02:40.459 +0000 UTC
Vector metric value: 328961.32
Vector metric timestamp: 2023-09-29 23:02:40.459 +0000 UTC
Vector metric value: 2311.23
Vector metric timestamp: 2023-09-29 23:02:40.459 +0000 UTC
Vector metric value: 1030776.1699999999
Vector metric timestamp: 2023-09-29 23:02:40.459 +0000 UTC
Vector metric value: 3401622.9499999997
time="2023-09-29 19:02:40" level=info msg="Indexing metric nodeCPUSecondsEnd-Workers" file="prometheus.go:105"
time="2023-09-29 19:02:40" level=debug msg="Indexing [8] documents" file="prometheus.go:106"
time="2023-09-29 19:02:40" level=info msg="File collected-metrics-21c314f2-b210-46ec-a139-904d8bd6fe4f/nodeCPUSecondsEnd-Workers.json created with 8 documents" file="prometheus.go:111"
time="2023-09-29 19:02:40" level=debug msg="Instant query: sum( node_cpu_seconds_total @start() and on (instance) label_replace(kube_node_role{role=\"worker\",role!=\"infra\"}, \"instance\", \"$1\", \"node\", \"(.+)\") ) by (mode)" file="prometheus.go:79"
Vector metric recorded end timestamp:  2023-09-29 23:02:40.458525025 +0000 UTC
Vector metric timestamp: 2023-09-29 23:02:40.459 +0000 UTC
Vector metric value: 76780657.36000001
Vector metric timestamp: 2023-09-29 23:02:40.459 +0000 UTC
Vector metric value: 109080.61000000002
Vector metric timestamp: 2023-09-29 23:02:40.459 +0000 UTC
Vector metric value: 270684.37000000005
Vector metric timestamp: 2023-09-29 23:02:40.459 +0000 UTC
Vector metric value: 15795.739999999996
Vector metric timestamp: 2023-09-29 23:02:40.459 +0000 UTC
Vector metric value: 328960.82999999996
Vector metric timestamp: 2023-09-29 23:02:40.459 +0000 UTC
Vector metric value: 2311.21
Vector metric timestamp: 2023-09-29 23:02:40.459 +0000 UTC
Vector metric value: 1030774.48
Vector metric timestamp: 2023-09-29 23:02:40.459 +0000 UTC
Vector metric value: 3401620.5300000007

```

**Comment by vishnuchalla** [comment]
```
to allow more options for instant queries to replace the currently hard-coded end timestamp, such that I can pick from: jobStart or jobEnd
```
Yeah, I think we can take this up in a different RFE, If its still needed.
