### ISSUE TITLE
[BUG] cpu usage prom queries for pods in metrics files do not include <name!=""> which is resulting in sum of container and pod cpu (double the value)

### ISSUE THREAD

**Issue by Noreen21** [cloud-bulldozer/kube-burner#460]
# Bug Description
cpu usage prom queries for pods do not include <name!=""> which is resulting in sum of container and pod cpu (double the value)
https://github.com/cloud-bulldozer/kube-burner/blob/master/cmd/kube-burner/ocp-config/metrics-report.yml

## **Describe the bug**
For instance, note the difference in the values reported for the queries below in grafana (screenshot attached)
sum(rate(container_cpu_usage_seconds_total{namespace="openshift-kube-controller-manager"}[2m])*100) by (pod)
sum(rate(container_cpu_usage_seconds_total{namespace="openshift-kube-controller-manager",name!=""}[2m])*100) by (pod)

From kube-burner:
The results from these two queries for the same workload can be seen below:

- query: topk(3, sum(irate(container_cpu_usage_seconds_total{ namespace="openshift-kube-controller-manager"}[2m])) by (pod))
  metricName: cpu-kube-controller-manager

- query: topk(3, sum(irate(container_cpu_usage_seconds_total{name!="", namespace="openshift-kube-controller-manager"}[2m])) by (pod))
  metricName: cpu-kube-controller-manager

Run | without | with
1 | 0.07784577971 | 0.04308086509
2 | 0.08111243782 | 0.06638296911
3 | 0.07045544606 | 0.02788249037
4 | 0.09040107115 | 0.04160751489
5 | 0.07223148943 | 0.04088077902
6 | 0.08045638938 | 0.03451377127

## **Screenshots or output**
![image](https://github.com/cloud-bulldozer/kube-burner/assets/91082159/892831a9-9d62-4de5-be12-d8cbfa2aade0)

If applicable, add screenshots or kube-burner output to help explain your problem.

**Comment by rsevilla87** [comment]
Thanks @Noreen21, good catch, for some reason I forgot to filter out containers with name!="" in this metrics profile as we are already doing in the other ones.
