### ISSUE TITLE
Endpoint for Elasticsearch does not work

### ISSUE THREAD

**Issue by KostasBitsakos** [cloud-bulldozer/kube-burner#474]
Hi,

in the configuration files of the kube-burner we have this   configuration point   

- esServers: [http://elastic-elk.apps.rsevilla.kube-burner.com].

The thing is that the address http://elastic-elk.apps.rsevilla.kube-burner.com does not lead anywhare.
Perhaps there is a new updated address?

**Comment by rsevilla87** [comment]
> Hi,
> 
> in the configuration files of the kube-burner we have this configuration point
> 
>     * esServers: [http://elastic-elk.apps.rsevilla.kube-burner.com].
> 
> 
> The thing is that the address http://elastic-elk.apps.rsevilla.kube-burner.com does not lead anywhare. Perhaps there is a new updated address?

That's a fake address just for demonstration purposes.
