### ISSUE TITLE
[RFE] Vanila k8s support to OCP wrappers for development purposes

### ISSUE THREAD

**Issue by josecastillolema** [cloud-bulldozer/kube-burner#520]
**Is your feature request related to a problem? Please describe.**
While it is clear that the OCP wrappers are designed for OpenShift it would be nice to be able to run them on vanila k8s clusters (i.e.: kind) with indexing disabled for development purposes.
For the workloads that reference OCP specific objects (i.e.: routes, imagestreams, etc.) this will not be possible.
It looks like i.e.: node-density does not reference any specific OCP objects so in principle it should be possible to run it once the prometheus requirement is relaxed.

**Comment by josecastillolema** [comment]
```
> ./kube-burner ocp node-density
time="2023-11-21 11:34:56" level=fatal msg="Error obtaining Prometheus information: the server could not find the requested resource" file="helpers.go:81"
```

**Comment by josecastillolema** [comment]
Bypassing the Prometheus requirement is not enough:
```
> ./kube-burner ocp node-density --metrics-endpoint=metrics-endpoint.yaml
time="2023-11-21 12:12:09" level=fatal msg="Error obtaining default ingress domain: the server could not find the requested resource" file="helpers.go:86"
```

**Comment by smalleni** [comment]
@rsevilla87 I have asked @josecastillolema to try and add web-burner scenarios directly into kube-burner itself but he is having issues testing the PR because we obviously assume operating agains an OCP cluster.  What are your thoughts here?
