### ISSUE TITLE
[BUG] Documentation does not explain where uuid for `kube-burner init` comes from nor how to generate one

### ISSUE THREAD

**Issue by RobertKrawitz** [cloud-bulldozer/kube-burner#78]
[The documentation](https://kube-burner.readthedocs.io/en/latest/cli/) does not explain the purpose of the mandatory `--uuid` argument, nor where to get/create it from.

It should also note that this uuid is the index into the Elastic Search database holding the results.

**Comment by Muscule** [comment]
Hello! When do you plan to fix it?
