### ISSUE TITLE
kube-burner release v0.9.1 binary for ppc64le does not work on Power9 ppc64le System

### ISSUE THREAD

**Issue by piyushgupta1551** [cloud-bulldozer/kube-burner#80]
**Output of `kube-burner `version**
This is the output from the binary made by me. the one from the github release does not run.
```
# ./kube-burner version
INFO[2021-06-10 10:45:54] Setting log level to info                    
Version: master
Git Commit: 137bd1bdd81b94ca0bfbc191d8101f96a8d8c663
Build Date: 2021-06-10-10:26:45
Go Version: go1.16.5
OS/Arch: linux ppc64le
```

**Describe the bug**
The binary taken from https://github.com/cloud-bulldozer/kube-burner/releases/download/v0.9.1/kube-burner-0.9.1-Linux-ppc64.tar.gz does not run on a IBM Power9 Server. Below is the error I get when I try to run it - 
```
10-06-2021T07:51:52 Downloading and extracting kube-burner binary
common.sh: line 76: ./kube-burner: cannot execute binary file: Exec format error
```

**To Reproduce**
1. Run the router-perf-V2 test via [ingress-performance.sh](https://github.com/cloud-bulldozer/e2e-benchmarking/blob/master/workloads/router-perf-v2/ingress-performance.sh)  defining the `ENGINE` variable as 'local' and specify the link for the ppc64le tarball in `KUBE_BURNER_RELEASE_URL` variable as https://github.com/cloud-bulldozer/kube-burner/releases/download/v0.9.1/kube-burner-0.9.1-Linux-ppc64.tar.gz

**Expected behavior**
Router Perf test should run successfully to completion.

**Screenshots or output**
Error seen when running ingress-performance.sh with above specifications - 
```
10-06-2021T07:51:52 Downloading and extracting kube-burner binary
common.sh: line 76: ./kube-burner: cannot execute binary file: Exec format error
```

**Additional context**
Upon further debugging the issue, it was seen that when I build the same binary from a Power9 server, it generates an `LSB executable binary` which runs fine whereas the official one available from github (https://github.com/cloud-bulldozer/kube-burner/releases/download/v0.9.1/kube-burner-0.9.1-Linux-ppc64.tar.gz) is an `MSB executable binary` gives an exec format error when running.
The sizes of both are also different but that may be due to the different go versions used to build.

My Binary -
```
# ls -ltra kube-burner 
-rwxr-xr-x. 1 1001 121 46562229 Jun 10 08:03 kube-burner
# file kube-burner 
kube-burner: ELF 64-bit LSB executable, 64-bit PowerPC or cisco 7500, version 1 (SYSV), statically linked, not stripped
```
The downloaded binary from official github release -
```
# ls -ltra kube-burner 
-rwxr-xr-x. 1 1001 121 51573114 Mar 26 11:28 kube-burner
# file kube-burner 
kube-burner: ELF 64-bit MSB executable, 64-bit PowerPC or cisco 7500, version 1 (SYSV), statically linked, not stripped 
```

**Comment by rsevilla87** [comment]
Hey @piyushgupta1551, thanks for raising this up, indeed there's a mistake in the goreleaser configuration. It seems I was wrongly compiling big endian binaries rather then little-endian as of your system. Will file a PR fixing it.

**Comment by rsevilla87** [comment]
Have created a new version with ppcle assets. Find them here:
https://github.com/cloud-bulldozer/kube-burner/releases/download/v0.10/kube-burner-0.10-Linux-ppc64le.tar.gz

```
$ curl -L https://github.com/cloud-bulldozer/kube-burner/releases/download/v0.10/kube-burner-0.10-Linux-ppc64le.tar.gz | tar xz
$ file kube-burner 
kube-burner: ELF 64-bit LSB executable, 64-bit PowerPC or cisco 7500, version 1 (SYSV), statically linked, Go BuildID=03thiRQ2SGaOH5K9-6Jc/ag7x4Nv5JTSzhD9aoky6/aYOMxj__E1AeAiBE2AUn/-JdPK5uOsCfbHlxiGxrZ, not stripped
```

Can you verify it works well in your system?

Thanks!

**Comment by piyushgupta1551** [comment]
Hey @rsevilla87 , thanks for the quick fix.

I can confirm that the new binary works fine for me on a P9 system.
```
# curl -L https://github.com/cloud-bulldozer/kube-burner/releases/download/v0.10/kube-burner-0.10-Linux-ppc64le.tar.gz | tar xz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   645  100   645    0     0   3161      0 --:--:-- --:--:-- --:--:--  3161
100 17.6M  100 17.6M    0     0  14.3M      0  0:00:01  0:00:01 --:--:-- 22.9M
# ./kube-burner -h
Kube-burner 🔥

Tool aimed at stressing a kubernetes cluster by creating or deleting lots of objects.

Usage:
  kube-burner [command]

Available Commands:
  check-alerts Evaluate alerts for the given time range
  completion   Generates completion scripts for bash shell
  destroy      Destroy old namespaces labeled with the given UUID.
  help         Help about any command
  index        Index metrics from the given time range
  init         Launch benchmark
  version      Print the version number of kube-burner

Flags:
  -h, --help               help for kube-burner
      --log-level string   Allowed values: debug, info, warn, error, fatal (default "info")

Use "kube-burner [command] --help" for more information about a command.
```

**Comment by rsevilla87** [comment]
Thanks!, closing this issue then.
