### ISSUE TITLE
[RFE] Metrics importer & exporter

### ISSUE THREAD

**Issue by rsevilla87** [cloud-bulldozer/kube-burner#87]
**Is your feature request related to a problem? Please describe.**
There're situations (specially in disconnected and restrictive environments) where there's no possibility of deploying a ES instance to index kube-burner metrics. We should add to kube-burner a mechanism to get & store those metrics, so a user can copy and share this data to be examined in a dashboard.

**Describe the solution you'd like**
kube-burner now has the feature o writing the collected metrics in different JSON files (one per query), we need to improve this feature to pack them in a single tarball or serialize into binary format (this is still TBD) required to improve data sharing and avoid having several files.
We'll also need to implement a new import mechanism in kube-burner able to read this information and send it to ES.

**Comment by rsevilla87** [comment]
FYI: I came up with this idea cc: @chaitanyaenr @jtaleric 
thoughts?

**Comment by jtaleric** [comment]
> **Is your feature request related to a problem? Please describe.**
> There're situations (specially in disconnected and restrictive environments) where there's no possibility of deploying a ES instance to index kube-burner metrics. We should add to kube-burner a mechanism to get & store those metrics, so a user can copy and share this data to be examined in a dashboard.
> 
> **Describe the solution you'd like**
> kube-burner now has the feature o writing the collected metrics in different JSON files (one per query), we need to improve this feature to pack them in a single tarball or serialize into binary format (this is still TBD) required to improve data sharing and avoid having several files.
> We'll also need to implement a new import mechanism in kube-burner able to read this information and send it to ES.

right - well I wonder if we want to have a re-index feature of the disconnected data, or simply have a simple python script to generate static graphs from the local json files? Disconnected might mean the data never leaves or can be connected, so having a way to review the results without actually connecting to a ES/infra...

**Comment by rsevilla87** [comment]
> > **Is your feature request related to a problem? Please describe.**
> > There're situations (specially in disconnected and restrictive environments) where there's no possibility of deploying a ES instance to index kube-burner metrics. We should add to kube-burner a mechanism to get & store those metrics, so a user can copy and share this data to be examined in a dashboard.
> > **Describe the solution you'd like**
> > kube-burner now has the feature o writing the collected metrics in different JSON files (one per query), we need to improve this feature to pack them in a single tarball or serialize into binary format (this is still TBD) required to improve data sharing and avoid having several files.
> > We'll also need to implement a new import mechanism in kube-burner able to read this information and send it to ES.
> 
> right - well I wonder if we want to have a re-index feature of the disconnected data, or simply have a simple python script to generate static graphs from the local json files? Disconnected might mean the data never leaves or can be connected, so having a way to review the results without actually connecting to a ES/infra...

That's a different idea my brain is still cooking. Implement a mechanism to quickly deploy&run all the stuff required to print the metrics collected by kube-burner (and persisted into a disk in this case).
I was thinking of creating a new container image having a combination of ES+Grafana wrapped by a script responsible of:

- Deploy the previous container
- Open & read the metrics tarball.
- Index them into ES
- Opening the grafana dashboard in the user's default browser using the UUID and start-end dates of the benchmark.

**Comment by chaitanyaenr** [comment]
Big +1 for this feature, there might be cases where users don't have access to a dedicated infrastructure ( Elasticsearch/Grafana )/can't connect to infrastructure running outside the network, having a way to capture the metrics in a tar ball which can loaded into a container for visualization is extremely helpful.

**Comment by rsevilla87** [comment]
The feature has been implemented in #92
