### ISSUE TITLE
Grafana dashboard

### ISSUE THREAD

**Issue by Muscule** [cloud-bulldozer/kube-burner#90]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I would like to get grafana dashboard represented on screenshot on this page https://www.openshift.com/blog/introducing-kube-burner-a-tool-to-burn-down-kubernetes-and-openshift?intcmp=701f2000000tjyaAAA

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by rsevilla87** [comment]
Hey @Muscule, as you may know the grafana dashboards are bound to the metrics you grab from Prometheus. The example I presented in that blog entry was taken after running the the workload "cluster-density" which is available here https://github.com/rsevilla87/kube-burner-workloads/tree/master/cluster-density

This workload was executed using the metric profile at https://github.com/rsevilla87/kube-burner-workloads/blob/master/metric-profiles/metrics-aggregated.yaml and the collected metrics were represented in grafana using the dashboard kube-burner-aggregated-latest.json available here https://github.com/rsevilla87/kube-burner-workloads/tree/master/dashboards#available-dashboards

Hope that helps.

**Comment by Muscule** [comment]
> Hey @Muscule, as you may know the grafana dashboards are bound to the metrics you grab from Prometheus. The example I presented in that blog entry was taken after running the the workload "cluster-density" which is available here https://github.com/rsevilla87/kube-burner-workloads/tree/master/cluster-density
> 
> This workload was executed using the metric profile at https://github.com/rsevilla87/kube-burner-workloads/blob/master/metric-profiles/metrics-aggregated.yaml and the collected metrics were represented in grafana using the dashboard kube-burner-aggregated-latest.json available here https://github.com/rsevilla87/kube-burner-workloads/tree/master/dashboards#available-dashboards
> 
> Hope that helps.

Could you add it into documentation, please?

**Comment by Muscule** [comment]
I think that https://github.com/rsevilla87/kube-burner-workloads should be united with this kube-burner for others not to ask these questions.

**Comment by rsevilla87** [comment]
> I think that https://github.com/rsevilla87/kube-burner-workloads should be united with this kube-burner for others not to ask these questions.

That's a good point, will do it ;)

**Comment by johnqa** [comment]
It would be also nice if those examples would be a little more documented and maybe have a version for a more vanilla kubernetes as they are very openshift currently.

Thanks

**Comment by rsevilla87** [comment]
FYI @johnqa @Muscule -> https://github.com/cloud-bulldozer/kube-burner/pull/94

**Comment by rsevilla87** [comment]
I've added more examples, some of them for OpenShift and others for vanilla k8s (Not very complex though). I don't have much time lately to commit this kind of changes, so every help will be appreciated:
