### ISSUE TITLE
Image Pull Secret

### ISSUE THREAD

**Issue by Muscule** [cloud-bulldozer/kube-burner#93]
**Is your feature request related to a problem? Please describe.**
For my cluster to be able to pull images it is important to use image pull secret. I use openshift.

**Describe the solution you'd like**
It would be great to have opportunity to create image pull secret automatically, when kube-burner creates project. This secret should exist in every kube-burner generated project.

**Describe alternatives you've considered**
I had to put image on every worker node. :(

**Comment by rsevilla87** [comment]
Hey @Muscule, you can those resources (service account linked to a docker-registry kind secret with permissions to pull from your registry) from a kube-burner job and then use, and then configure your pods to use those service accounts.

**Comment by Muscule** [comment]
I suppose, some misunderstanding happened. I added image pull secret to the deployment objectTemplate, I created image pull secret yaml-file. I added a line "- objectTemplate: objectTemplates/secret.yml" in cfg.yml into the first job. But the secret is not created by the kube-burner. How can I make kube-burner create this secret in each namespace generated by kube-burner?

**Comment by Muscule** [comment]
Well, I added creation of secrets successfully. I added into cfg.yml in creation job:

 objects:

      - objectTemplate: objectTemplates/secret.yml
        replicas: 20

Then I created objectTemplates/secret.yml.

It did the job.
